---
abstract: 'Generate best practice release-only tests'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Remove: 1.42
  File::Spec: 0.8
  Perl::MinimumVersion: 1.2
  Pod::Simple: 3.07
  Test::CPAN::Meta: 0.12
  Test::CheckChanges: 0.08
  Test::DistManifest: 1.003
  Test::MinimumVersion: 0.008
  Test::More: 0.42
  Test::Pod: 1.26
  Test::Pod::Coverage: 1.08
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::XT
name: Test-XT
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.8.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Test-XT
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Test-XT
version: 0.04
